# Generated by Django 2.2.7 on 2019-11-16 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todopost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='finished',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 11, 24, 23, 180586)),
        ),
    ]
