# Generated by Django 2.2.7 on 2019-11-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todopost', '0002_post_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='finished',
            field=models.DateTimeField(),
        ),
    ]
