# Generated by Django 2.2.7 on 2019-11-21 12:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todopost', '0004_auto_20191116_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='finished',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 12, 43, 54, 433172, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todopost.Post')),
                ('with_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
